version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env-not-dev
    ports:
      - 5433:5432
    command: ["-p", "5432"]

  organizations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: organizations_app
    env_file:
      - .env-not-dev
    depends_on:
      - db
    ports:
      - 8000:8000