version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env-not-dev
    ports:
      - 5433:5432
    command: ["-p", "5432"]

  organizations:
    image: organizations_image
    build:
      context: .
    container_name: organizations_app
    env_file:
      - .env-not-dev
    depends_on:
      - db
    command: ["/organizations/start_fastapi.sh"]
    ports:
      - 8000:8000